// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpA4KOzCCGULWpDx3A3JEXpxGCa4gNTrI',
    appId: '1:1097359980771:web:af227bc0a8bdcd0ae02dd6',
    messagingSenderId: '1097359980771',
    projectId: 'sms-app-project-415923',
    authDomain: 'sms-app-project-415923.firebaseapp.com',
    databaseURL: 'https://sms-app-project-415923-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sms-app-project-415923.appspot.com',
    measurementId: 'G-GJ3RF6JTWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2S52QCyAmwho-aFbuHEi--3NbrxPHMAk',
    appId: '1:1097359980771:android:aa0669b5f32f3f9de02dd6',
    messagingSenderId: '1097359980771',
    projectId: 'sms-app-project-415923',
    databaseURL: 'https://sms-app-project-415923-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sms-app-project-415923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUwpeva0yXm6bTM7em3H2tiwWTnlAQGUQ',
    appId: '1:1097359980771:ios:d6322b7b307799d6e02dd6',
    messagingSenderId: '1097359980771',
    projectId: 'sms-app-project-415923',
    databaseURL: 'https://sms-app-project-415923-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sms-app-project-415923.appspot.com',
    iosBundleId: 'com.example.uiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUwpeva0yXm6bTM7em3H2tiwWTnlAQGUQ',
    appId: '1:1097359980771:ios:b838c7329d8a6db5e02dd6',
    messagingSenderId: '1097359980771',
    projectId: 'sms-app-project-415923',
    databaseURL: 'https://sms-app-project-415923-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sms-app-project-415923.appspot.com',
    iosBundleId: 'com.example.uiFlutter.RunnerTests',
  );
}
