runtime: python312
env: standard
entrypoint: hypercorn -b :$PORT main:app --graceful-timeout 600
# gunicorn -w 4 -k gevent --bind :$PORT main:app --timeout 600
# gunicorn -b :$PORT main:app --timeout 600

# runtime_config:
#     operating_system: "ubuntu22"
#     runtime_version: "3.12"

service: default
instance_class: B2 # Choose an instance class

automatic_scaling:
  max_instances: 1

handlers:
- url: /.*          # Direct all traffic to the main app
  script: auto
  secure: always    # Enforce HTTPS


# Environment variables:
env_variables:
  FLASK_ENV: 'production'
  # SECRET_KEY: 'your-secret-key'
